In [1]:
from base import Rangel
from rangel import RangeCollection
import numpy as np

In [2]:
rng_pt1 = Rangel(locs=[0, 4, 6, 9, 3, 13])
rng_pt2 = Rangel(locs=[1, 4, 9])

In [3]:
rng_ln1 = Rangel(begs=[0, 3, 8, 12, 14], ends=[3, 5, 12, 13, 20], closed='left_mod')
rng_ln2 = Rangel(begs=[-2, 0, 8, 14], ends=[0, 5, 9, 13], closed='right_mod')

In [4]:
rng_ln1, rng_pt1, rng_ln1.intersecting(rng_pt1)

(0, [ 0.000,  3.000)
 1, [ 3.000,  5.000]
 2, [ 8.000, 12.000)
 3, [12.000, 13.000]
 4, [14.000, 20.000]
 Rangel(5 ungrouped linear monotonic events, closed=left_mod),
 0, @  0.000
 1, @  4.000
 2, @  6.000
 3, @  9.000
 4, @  3.000
 5, @ 13.000
 Rangel(6 ungrouped point events),
 array([[ True, False, False, False, False, False],
        [False,  True, False, False,  True, False],
        [False, False, False,  True, False, False],
        [False, False, False, False, False,  True],
        [False, False, False, False, False, False]]))

In [5]:
rng_ln1, rng_ln2, rng_ln1.intersecting(rng_ln2)

(0, [ 0.000,  3.000)
 1, [ 3.000,  5.000)
 2, [ 8.000, 12.000)
 3, [12.000, 13.000)
 4, [14.000, 20.000)
 Rangel(5 ungrouped linear monotonic events, closed=left),
 0, [-2.000,  0.000]
 1, ( 0.000,  5.000]
 2, [ 8.000,  9.000]
 3, [13.000, 14.000]
 Rangel(4 ungrouped linear monotonic events, closed=right_mod),
 array([[ True,  True, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False, False],
        [False, False, False,  True]]))

In [16]:
%%timeit
rng1.intersecting(rng2)

10.1 µs ± 307 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
rc1 = RangeCollection(begs=[0, 4, 6, 9, 3])
rc1

(0.000, 0.000]
(4.000, 4.000]
(6.000, 6.000]
(9.000, 9.000]
(3.000, 3.000]
RangeCollection(5 numeric ranges, closed=right, centers=true_centers)

In [13]:
rc2 = RangeCollection(begs=[1, 4, 9])
rc2

(1.000, 1.000]
(4.000, 4.000]
(9.000, 9.000]
RangeCollection(3 numeric ranges, closed=right, centers=true_centers)

In [15]:
%%timeit
rc1.intersecting(rc2)

153 µs ± 4.47 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
%%timeit
Rangel(begs=[0, 4, 6, 9, 3], ends=[1, 5, 7, 10, 4])

46.1 µs ± 549 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
%%timeit
RangeCollection(begs=[0, 4, 6, 9, 3], ends=[1, 5, 7, 10, 4])

42.6 µs ± 435 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
a = np.zeros((5,3), dtype=bool)
a

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [18]:
a = np.zeros((5,3), dtype=bool)
np.logical_or(a, True, out=a, where=np.array([True, False, False, True, True]).reshape(-1,1))
a

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
a = np.zeros((5,3), dtype=bool)
b = np.array([True, False, False, True, True]).reshape(-1,1)
a | b

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])